### ISSUE TITLE
Support for icon rotation by properly aligning them to their vertical center

### ISSUE THREAD

**Issue by darsain** [gregoryloucas/Fontstrap#44]
Now this is silly, and feel free to hit the close button :), but I wanted to use icon-refresh as a loading animation. I've created a `.rotate` class:

``` css
@-webkit-keyframes rotate {
  from { -webkit-transform: rotate(0deg); }
  to { -webkit-transform: rotate(360deg); }
}
@keyframes rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
.rotate {
    display: inline-block;
    -webkit-animation-name: rotate;
    animation-name: rotate;
    -webkit-animation-duration: 1000ms;
    animation-duration: 1000ms;
    -webkit-animation-iteration-count:infinite;
    animation-iteration-count:infinite;
    -webkit-animation-timing-function:linear;
    animation-timing-function:linear;
}
```

Which, when applied to an icon, should make them rotate. The default icon styles however makes the animation wobbly due to icons not being in their exact vertical center.

The result with my quick-fix can be seen here: http://jsfiddle.net/RXMVN/ (from some reason icons don't load in other browsers than Chrome)

Do you feel like this is something worth chasing ? :)
